title: "Shafayet Nur"
name: "Shafayet Nur"
description: "Bioinformatics Researcher • Teaching Assistant"
url: "https://shafayet-nur.github.io"
baseurl: ""
repository: "shafayet-nur/shafayet-nur.github.io"

# Theme and plugins
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

# Author info
author:
  name: "Shafayet Nur"
  avatar: "/assets/images/profile.jpg"
  bio: "Ph.D. Student • Graduate Teaching Assistant  
  Northern Illinois University, USA"
  location: "DeKalb, Illinois, USA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/shafayet-nur-156941201/"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=Wup-DigAAAAJ&hl=en&oi=ao"
    - label: "ResearchGate"
      icon: "fas fa-flask"
      url: "https://www.researchgate.net/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:shafayetnur.abir@gmail.com"


# Navigation
main:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Teaching"
    url: /teaching/
  - title: "Contact"
    url: /contact/

# Footer links
footer:
  - label: "© 2025 Shafayet Nur"
    url: "https://shafayet-nur.github.io"

sass:
  style: compressed

include:
  - assets/css/custom.css

# Markdown settings
markdown: kramdown
highlighter: rouge
paginate: 5
