title: "Shafayet Nur"
description: "Researcher • Teaching Assistant • Bioinformatics Enthusiast"
url: "https://shafayet-nur.github.io"
theme: jekyll-theme-minimal

author:
  name: "Shafayet Nur"
  email: your_email@example.com
